hm_carro:
    path:     /carro/
    defaults: { _controller: HmCarroBundle:Default:index }
    
hm_carro_add:
    path:     /carro/add
    defaults: { _controller: HmCarroBundle:Default:add }
    
hm_carro_editar:
    path:     /carro/editar/{id}
    defaults: { _controller: HmCarroBundle:Default:editar }
    requirements: { _method: post|put }
    
hm_carro_delete:
    path:     /carro/delete/{id}
    defaults: { _controller: HmCarroBundle:Default:delete }
    requirements: {_method: DELETE}
    
hm_carro_visualizar:
    path:     /carro/visualizar/{id}
    defaults: { _controller: HmCarroBundle:Default:visualizar }
    
hm_carro_up:
    path:     /carro/up/{id}
    defaults: { _controller: HmCarroBundle:Default:upload }
    requirements: { _method: post|put }